# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_cards',
                'doc_host': 'https://skyrocket126.github.io',
                'git_url': 'https://github.com/skyrocket126/nbdev_cards',
                'lib_path': 'nbdev-cards'},
  'syms': { 'nbdev-cards.card': { 'nbdev-cards.card.Card': ('cards.html#card', 'nbdev-cards/card.py'),
                                  'nbdev-cards.card.Card.__eq__': ('cards.html#card.__eq__', 'nbdev-cards/card.py'),
                                  'nbdev-cards.card.Card.__gt__': ('cards.html#card.__gt__', 'nbdev-cards/card.py'),
                                  'nbdev-cards.card.Card.__init__': ('cards.html#card.__init__', 'nbdev-cards/card.py'),
                                  'nbdev-cards.card.Card.__lt__': ('cards.html#card.__lt__', 'nbdev-cards/card.py'),
                                  'nbdev-cards.card.Card.__str__': ('cards.html#card.__str__', 'nbdev-cards/card.py')},
            'nbdev-cards.deck': { 'nbdev-cards.deck.Deck': ('deck.html#deck', 'nbdev-cards/deck.py'),
                                  'nbdev-cards.deck.Deck.__contains__': ('deck.html#deck.__contains__', 'nbdev-cards/deck.py'),
                                  'nbdev-cards.deck.Deck.__init__': ('deck.html#deck.__init__', 'nbdev-cards/deck.py'),
                                  'nbdev-cards.deck.Deck.__len__': ('deck.html#deck.__len__', 'nbdev-cards/deck.py'),
                                  'nbdev-cards.deck.Deck.__str__': ('deck.html#deck.__str__', 'nbdev-cards/deck.py')}}}
