name: Upload to ukpypi

on:
  push:
    tags:
      - 'v*'  # v0.0.1 などのタグが対象

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          pip install build nbdev
          pip install -e .
          curl -fsSL https://quarto.org/download/latest/quarto-linux-amd64.deb -o quarto.deb
          sudo dpkg -i quarto.deb 

      - name: Prepare version
        run: |
          nbdev_prepare

      - name: Build package
        run: |
          python -m build

      - name: Setup SSH for rsync
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PROXY1_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa_proxy1
          echo "${{ secrets.REPOG221_SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519_repog221
          chmod 600 ~/.ssh/id_rsa_proxy1 ~/.ssh/id_ed25519_repog221
          cat <<EOF > ~/.ssh/config
          Host proxy1
            HostName proxy1.ukw.jp
            User your_user_name
            IdentityFile ~/.ssh/id_rsa_proxy1
            IdentitiesOnly yes
            HostkeyAlgorithms +ssh-rsa
            PubkeyAcceptedAlgorithms +ssh-rsa
            StrictHostKeyChecking no

          Host repog221
            HostName repog221.ukw.jp
            User universal
            IdentityFile ~/.ssh/id_ed25519_repog221
            ProxyJump proxy1
            IdentitiesOnly yes
            StrictHostKeyChecking no
          EOF
          chmod 600 ~/.ssh/config

      - name: Upload to internal PyPI
        run: |
          rsync -avz dist/*.tar.gz repog221:/var/www/html/repos/ukpypi/nbdev-cards/
